export const SUBJECT_NAMES = [
  "Administration",
  "Allowances",
  "BAM Committee",
  "Circular State BA",
  "Coach Education",
  "Coaches",
  "Commercial",
  "Constitution",
  "Council",
  "Development",
  "Disciplinary Committee",
  "Employee Handbook",
  "EXCO Decision",
  "Finance",
  "Finance Committee",
  "Governance",
  "Hostel",
  "HR",
  "JET",
  "Legal Committee",
  "Media",
  "MEMO",
  "National Junior Players",
  "National Players",
  "National Senior Players",
  "National Tournaments",
  "Organisation regulations",
  "Others",
  "Performance Committee",
  "Policy",
  "Ranking",
  "State BA",
  "State Grants",
  "State Players",
  "Strategy",
  "SUKMA",
  "Tangkis 2030",
  "Technical Official",
  "Welfare Committee",
] as const;

export type SubjectName = (typeof SUBJECT_NAMES)[number];

export const OTHERS_SUBJECT = "Others" as const;
